# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFindSpareParts():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_findSpareParts(self):
    self.driver.get("https://www.ikea.com/ca/en/")
    self.driver.execute_script("window.scrollTo(0,4704)")
    self.driver.execute_script("window.scrollTo(0,15008)")
    self.driver.find_element(By.LINK_TEXT, "Spare parts").click()
    self.driver.find_element(By.ID, "search-field").click()
    self.driver.find_element(By.ID, "search-field").send_keys("116546")
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".HighlightText__StyledSpanHighlight-sc-1okdef6-0:nth-child(2)")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, ".DisplaySearchItems__FlexContainer-sc-yftuok-1").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn__label:nth-child(1)").click()
    self.driver.find_element(By.ID, "search-field").click()
    self.driver.find_element(By.CSS_SELECTOR, ".search__clear > .btn__inner").click()
    self.driver.find_element(By.ID, "search-field").send_keys("Ethan")
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".btn--primary > .btn__inner")
    assert len(elements) == 0
  
