# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSearchForProducts():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_searchForProducts(self):
    self.driver.get("https://www.ikea.com/ca/en/")
    self.driver.find_element(By.NAME, "q").click()
    self.driver.find_element(By.NAME, "q").send_keys("Blahaj")
    self.driver.find_element(By.NAME, "q").send_keys(Keys.ENTER)
    self.driver.execute_script("window.scrollTo(0,608)")
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".plp-product-list__products > .plp-fragment-wrapper:nth-child(1) .pip-btn:nth-child(1)")
    assert len(elements) > 0
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.ID, "clear-input").click()
    self.driver.find_element(By.NAME, "q").click()
    self.driver.find_element(By.NAME, "q").send_keys("Ethan")
    self.driver.find_element(By.NAME, "q").send_keys(Keys.ENTER)
    self.driver.execute_script("window.scrollTo(0,208)")
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".plp-product-list__products > .plp-fragment-wrapper:nth-child(1) .pip-btn:nth-child(1)")
    assert len(elements) == 0
  
