# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSelectNearestStore():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_selectNearestStore(self):
    self.driver.get("https://www.ikea.com/ca/en/")
    self.driver.find_element(By.CSS_SELECTOR, ".hnf-location__btn-wrapper--postalcode > .hnf-btn--small .hnf-btn__label").click()
    self.driver.find_element(By.ID, "hnf-txt-postalcodepicker-postcode").send_keys("T2W5C6")
    self.driver.find_element(By.ID, "hnf-txt-postalcodepicker-postcode").send_keys(Keys.ENTER)
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".hnf-location__btn-wrapper:nth-child(1) > .hnf-location__store > .hnf-btn__inner")))
    self.driver.find_element(By.CSS_SELECTOR, ".hnf-location__btn-wrapper:nth-child(1) > .hnf-location__store .hnf-btn__label").click()
    self.driver.find_element(By.CSS_SELECTOR, "#hnf-btn-storepicker-visit-store > .hnf-btn__inner").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, "#\\39 d995680-3731-11ec-ab46-0147eaa40288 h2")
    assert len(elements) > 0
  
